"""Application version / build metadata."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from paths import build_info_path, is_frozen

# Bumped for tagged stable releases; preview builds override via build_info.json.
APP_VERSION = "0.1.0"
GITHUB_REPO = "mythorath/macro-review"
GITHUB_URL = f"https://github.com/{GITHUB_REPO}"


@dataclass(frozen=True)
class BuildInfo:
    version: str
    channel: str
    commit: str
    built_at: str
    repo: str

    @property
    def display(self) -> str:
        parts = [f"v{self.version}"]
        if self.channel and self.channel != "stable":
            parts.append(f"({self.channel})")
        if self.commit and self.commit not in {"", "unknown", "dev"}:
            parts.append(self.commit[:7])
        return " ".join(parts)

    def to_dict(self) -> dict[str, str]:
        return {
            "version": self.version,
            "channel": self.channel,
            "commit": self.commit,
            "built_at": self.built_at,
            "repo": self.repo,
        }


def _dev_build_info() -> BuildInfo:
    return BuildInfo(
        version=APP_VERSION,
        channel="dev",
        commit="dev",
        built_at=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        repo=GITHUB_REPO,
    )


def load_build_info() -> BuildInfo:
    # build_info.json is generated by packaging/build.ps1 and may remain in a
    # developer checkout. Only frozen builds should consume release metadata.
    if not is_frozen():
        return _dev_build_info()

    path = build_info_path()
    if path.is_file():
        try:
            data = json.loads(path.read_text(encoding="utf-8-sig"))
        except (OSError, json.JSONDecodeError):
            data = {}
        if isinstance(data, dict) and data:
            return BuildInfo(
                version=str(data.get("version") or APP_VERSION),
                channel=str(data.get("channel") or "preview"),
                commit=str(data.get("commit") or "unknown"),
                built_at=str(data.get("built_at") or ""),
                repo=str(data.get("repo") or GITHUB_REPO),
            )
    info = _dev_build_info()
    return BuildInfo(
        version=info.version,
        channel="preview",
        commit=info.commit,
        built_at=info.built_at,
        repo=info.repo,
    )


def default_update_channel() -> str:
    channel = load_build_info().channel
    if channel == "stable":
        return "stable"
    if channel in {"preview", "dev"}:
        return "preview" if is_frozen() else "stable"
    return "stable"


def write_build_info(
    path: Path,
    *,
    version: str,
    channel: str,
    commit: str,
    repo: str = GITHUB_REPO,
) -> None:
    payload = {
        "version": version,
        "channel": channel,
        "commit": commit,
        "built_at": datetime.now(timezone.utc).isoformat(),
        "repo": repo,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
